# Generated by Django 4.2.2 on 2023-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_direct_ancestor',
            field=models.BooleanField(default=False, verbose_name='прямой предок'),
        ),
    ]
